name: MemeAnnounce
version: '${project.version}'
main: net.wycre.memeannounce.Main
api-version: 1.18
authors: [ wycre ]
description: Adds a command that will broadcast a random message specified in config.yml. With a number of variatons.
website: www.wycre.net
commands:
  meme:
    description: Broadcast a random humorous message to the server
    usage: /<command> [fill/static/dynamic] [message key] [fill]
permissions:
  wycre.meme.static:
    description: use of static message sending
    default: not op
  wycre.meme.dynamic:
    description: use of dynamic message sending
    default: not op
  wycre.meme.choose:
    description: allows user to pick the message to be sent
    default: op
  wycre.meme.cooldown:
    description: bypasses the cooldown associated with the command
    default: op
  wycre.meme.*:
    description: wildcard
    default: op
    children:
      wycre.meme.static: true
      wycre.meme.dynamic: true
      wycre.meme.choose: true
      wycre.meme.cooldown: true